---
- name: OCP | Upgrade Cleanup
  hosts: all
  tasks:
    - name: OCP | Upgrade Cleanup | Include Tasks for Enable Excluders
      include_tasks: tasks/enable-excluders.yml

    - name: OCP | Upgrade Cleanup | Clear the yum cache
      command: 'yum clean all'
      args:
        warn: no
